In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt




path=r"J:\Downloads\Visadataset.csv"
visa_df=pd.read_csv(path)
visa_df


case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N   
1         EZYV02      Asia              Master's                  Y   
2         EZYV03      Asia            Bachelor's                  N   
3         EZYV04      Asia            Bachelor's                  N   
4         EZYV05    Africa              Master's                  Y   
...          ...       ...                   ...                ...   
25475  EZYV25476      Asia            Bachelor's                  Y   
25476  EZYV25477      Asia           High School                  Y   
25477  EZYV25478      Asia              Master's                  Y   
25478  EZYV25479      Asia              Master's                  Y   
25479  EZYV25480      Asia            Bachelor's                  Y   

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007   
1                         N             2412         2002   
2                         Y            44444         2008   
3                         N               98         1897   
4                         N             1082         2005   
...                     ...              ...          ...   
25475                     Y             2601         2008   
25476                     N             3274         2006   
25477                     N             1121         1910   
25478                     Y             1918         1887   
25479                     N             3195         1960   

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y   
1                Northeast       83425.6500         Year                  Y   
2                     West      122996.8600         Year                  Y   
3                     West       83434.0300         Year                  Y   
4                    South      149907.3900         Year                  Y   
...                    ...              ...          ...                ...   
25475                South       77092.5700         Year                  Y   
25476            Northeast      279174.7900         Year                  Y   
25477                South      146298.8500         Year                  N   
25478                 West       86154.7700         Year                  Y   
25479              Midwest       70876.9100         Year                  Y   

      case_status  
0          Denied  
1       Certified  
2          Denied  
3          Denied  
4       Certified  
...           ...  
25475   Certified  
25476   Certified  
25477   Certified  
25478   Certified  
25479   Certified  

[25480 rows x 12 columns]

In [7]:
visa_df.head()

case_id continent education_of_employee has_job_experience  \
0  EZYV01      Asia           High School                  N   
1  EZYV02      Asia              Master's                  Y   
2  EZYV03      Asia            Bachelor's                  N   
3  EZYV04      Asia            Bachelor's                  N   
4  EZYV05    Africa              Master's                  Y   

  requires_job_training  no_of_employees  yr_of_estab region_of_employment  \
0                     N            14513         2007                 West   
1                     N             2412         2002            Northeast   
2                     Y            44444         2008                 West   
3                     N               98         1897                 West   
4                     N             1082         2005                South   

   prevailing_wage unit_of_wage full_time_position case_status  
0         592.2029         Hour                  Y      Denied  
1       83425.6500         Year                  Y   Certified  
2      122996.8600         Year                  Y      Denied  
3       83434.0300         Year                  Y      Denied  
4      149907.3900         Year                  Y   Certified

- shape
- head 
- tale 
- shape 
- size
- columns
- dtype
- isnull
- isnull().sum()
- isna
- info

In [8]:
visa_df.isna()

case_id  continent  education_of_employee  has_job_experience  \
0        False      False                  False               False   
1        False      False                  False               False   
2        False      False                  False               False   
3        False      False                  False               False   
4        False      False                  False               False   
...        ...        ...                    ...                 ...   
25475    False      False                  False               False   
25476    False      False                  False               False   
25477    False      False                  False               False   
25478    False      False                  False               False   
25479    False      False                  False               False   

       requires_job_training  no_of_employees  yr_of_estab  \
0                      False            False        False   
1                      False            False        False   
2                      False            False        False   
3                      False            False        False   
4                      False            False        False   
...                      ...              ...          ...   
25475                  False            False        False   
25476                  False            False        False   
25477                  False            False        False   
25478                  False            False        False   
25479                  False            False        False   

       region_of_employment  prevailing_wage  unit_of_wage  \
0                     False            False         False   
1                     False            False         False   
2                     False            False         False   
3                     False            False         False   
4                     False            False         False   
...                     ...              ...           ...   
25475                 False            False         False   
25476                 False            False         False   
25477                 False            False         False   
25478                 False            False         False   
25479                 False            False         False   

       full_time_position  case_status  
0                   False        False  
1                   False        False  
2                   False        False  
3                   False        False  
4                   False        False  
...                   ...          ...  
25475               False        False  
25476               False        False  
25477               False        False  
25478               False        False  
25479               False        False  

[25480 rows x 12 columns]

In [13]:
visa_df.isnull()

case_id  continent  education_of_employee  has_job_experience  \
0        False      False                  False               False   
1        False      False                  False               False   
2        False      False                  False               False   
3        False      False                  False               False   
4        False      False                  False               False   
...        ...        ...                    ...                 ...   
25475    False      False                  False               False   
25476    False      False                  False               False   
25477    False      False                  False               False   
25478    False      False                  False               False   
25479    False      False                  False               False   

       requires_job_training  no_of_employees  yr_of_estab  \
0                      False            False        False   
1                      False            False        False   
2                      False            False        False   
3                      False            False        False   
4                      False            False        False   
...                      ...              ...          ...   
25475                  False            False        False   
25476                  False            False        False   
25477                  False            False        False   
25478                  False            False        False   
25479                  False            False        False   

       region_of_employment  prevailing_wage  unit_of_wage  \
0                     False            False         False   
1                     False            False         False   
2                     False            False         False   
3                     False            False         False   
4                     False            False         False   
...                     ...              ...           ...   
25475                 False            False         False   
25476                 False            False         False   
25477                 False            False         False   
25478                 False            False         False   
25479                 False            False         False   

       full_time_position  case_status  
0                   False        False  
1                   False        False  
2                   False        False  
3                   False        False  
4                   False        False  
...                   ...          ...  
25475               False        False  
25476               False        False  
25477               False        False  
25478               False        False  
25479               False        False  

[25480 rows x 12 columns]

In [14]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   case_id                25480 non-null  object 
 1   continent              25480 non-null  object 
 2   education_of_employee  25480 non-null  object 
 3   has_job_experience     25480 non-null  object 
 4   requires_job_training  25480 non-null  object 
 5   no_of_employees        25480 non-null  int64  
 6   yr_of_estab            25480 non-null  int64  
 7   region_of_employment   25480 non-null  object 
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object 
 10  full_time_position     25480 non-null  object 
 11  case_status            25480 non-null  object 
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB


In [18]:
visa_df.take([100,200,300])

case_id continent education_of_employee has_job_experience  \
100  EZYV101      Asia              Master's                  Y   
200  EZYV201      Asia             Doctorate                  Y   
300  EZYV301      Asia              Master's                  Y   

    requires_job_training  no_of_employees  yr_of_estab region_of_employment  \
100                     N             2227         2007            Northeast   
200                     N             3282         1979                 West   
300                     N             3268         2012              Midwest   

     prevailing_wage unit_of_wage full_time_position case_status  
100         28243.79         Year                  Y   Certified  
200         74441.11         Year                  Y   Certified  
300        101371.21         Year                  Y   Certified

In [2]:
visa_df.take([100,200,300])

case_id continent education_of_employee has_job_experience  \
100  EZYV101      Asia              Master's                  Y   
200  EZYV201      Asia             Doctorate                  Y   
300  EZYV301      Asia              Master's                  Y   

    requires_job_training  no_of_employees  yr_of_estab region_of_employment  \
100                     N             2227         2007            Northeast   
200                     N             3282         1979                 West   
300                     N             3268         2012              Midwest   

     prevailing_wage unit_of_wage full_time_position case_status  
100         28243.79         Year                  Y   Certified  
200         74441.11         Year                  Y   Certified  
300        101371.21         Year                  Y   Certified

In [3]:
visa_df

case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N   
1         EZYV02      Asia              Master's                  Y   
2         EZYV03      Asia            Bachelor's                  N   
3         EZYV04      Asia            Bachelor's                  N   
4         EZYV05    Africa              Master's                  Y   
...          ...       ...                   ...                ...   
25475  EZYV25476      Asia            Bachelor's                  Y   
25476  EZYV25477      Asia           High School                  Y   
25477  EZYV25478      Asia              Master's                  Y   
25478  EZYV25479      Asia              Master's                  Y   
25479  EZYV25480      Asia            Bachelor's                  Y   

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007   
1                         N             2412         2002   
2                         Y            44444         2008   
3                         N               98         1897   
4                         N             1082         2005   
...                     ...              ...          ...   
25475                     Y             2601         2008   
25476                     N             3274         2006   
25477                     N             1121         1910   
25478                     Y             1918         1887   
25479                     N             3195         1960   

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y   
1                Northeast       83425.6500         Year                  Y   
2                     West      122996.8600         Year                  Y   
3                     West       83434.0300         Year                  Y   
4                    South      149907.3900         Year                  Y   
...                    ...              ...          ...                ...   
25475                South       77092.5700         Year                  Y   
25476            Northeast      279174.7900         Year                  Y   
25477                South      146298.8500         Year                  N   
25478                 West       86154.7700         Year                  Y   
25479              Midwest       70876.9100         Year                  Y   

      case_status  
0          Denied  
1       Certified  
2          Denied  
3          Denied  
4       Certified  
...           ...  
25475   Certified  
25476   Certified  
25477   Certified  
25478   Certified  
25479   Certified  

[25480 rows x 12 columns]

In [6]:
visa_df["continent"]     # here we get in series form

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...  
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [7]:
visa_df[["continent"]]         # by applying list we get in dataFrame

continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]

In [13]:
visa_df.loc[:,["continent"]]    

continent
0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
...         ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia

[25480 rows x 1 columns]

In [15]:
 set = {0, 0, "a1", 0, 9}
print(set)

{0, 9, 'a1'}


In [16]:
 print (0xA + 0xB + 0xC)

33


In [1]:
"2"==2

False

In [2]:
str = [(1, 1), (2, 2), (3, 3)]
type(str)

list

In [3]:
MANGO = APPLE

NameError: name 'APPLE' is not defined

In [4]:
my_list = [1, 2, 3] 
print(my_list[3]) 


IndexError: list index out of range

In [5]:
my_list = [1, 2, 3]
my_list.remove(4) 


ValueError: list.remove(x): x not in list

In [6]:
 my_dict ={'name': 'Alice', 'age':23} 
print(my_dict['address']) 


KeyError: 'address'

In [7]:
print ("Hello World) 

SyntaxError: unterminated string literal (detected at line 1) (2311437580.py, line 1)

In [9]:
import os 
os.getcwd()

'C:\\Users\\Madhu\\naresh it\\EDA'

In [ ]:
C:\Users\Madhu\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)


C:\Users\Madhu\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code

In [10]:
import numpy as np

In [34]:
x=[[10,20,90],[30,40,100],[50,60,110],[70,80,120]]
y=np.array(x)
type(y)
print(y.ndim)
print(y.shape)
print(y)
print()
print()
print(y.T)
print()
print()
print(y.reshape(3,4))
print()
print()
print(y.reshape(1,12))
print()
print()
print(y.reshape(12,1))

2
(4, 3)
[[ 10  20  90]
 [ 30  40 100]
 [ 50  60 110]
 [ 70  80 120]]


[[ 10  30  50  70]
 [ 20  40  60  80]
 [ 90 100 110 120]]


[[ 10  20  90  30]
 [ 40 100  50  60]
 [110  70  80 120]]


[[ 10  20  90  30  40 100  50  60 110  70  80 120]]


[[ 10]
 [ 20]
 [ 90]
 [ 30]
 [ 40]
 [100]
 [ 50]
 [ 60]
 [110]
 [ 70]
 [ 80]
 [120]]


In [17]:
print(y[3,1])

80


In [22]:
dir("np")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [35]:
word = "Python"
print(word[0])


P


In [38]:
a = 5
b = 2.5
c = "Hello"
result = a * b
print(c + str(result))


TypeError: 'list' object is not callable

In [40]:
S1 = "Python"
S2 = "is amazing!"
result = S1*3 + S2
print(result)


PythonPythonPythonis amazing!


In [53]:
x = 5
y = 2
result = x ** y /3
print(result)



8.333333333333334


In [46]:
n = [1,2,3,4,5]
n.pop(2)


3

In [51]:
person = {"name":"John","age":30,"city":"NewYork"}
print(person["age"])


30


In [70]:
i = 1
while True:
   	    if i%3 == 0:
       		break
        i=i+1
   	    print(i)
    

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 5)

In [71]:
 fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
                    print(fruit)


apple
banana
cherry


In [72]:
num = 5
while num > 0:
            print(num)
            num -= 1
            if  num == 3:
                        break


5
4
